apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: minio-operator-leader-election-rolebinding
  namespace: {{ .Values.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: minio-operator-leader-election-role
subjects:
- kind: ServiceAccount
  name: minio-operator-controller-manager
  namespace: {{ .Values.namespace }}
