---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: minio-operator-manager-role
rules:
- apiGroups:
  - minio.bob.com
  resources:
  - miniojobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - minio.bob.com
  resources:
  - miniojobs/finalizers
  verbs:
  - update
- apiGroups:
  - minio.bob.com
  resources:
  - miniojobs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - minio.bob.com
  resources:
  - minios
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - minio.bob.com
  resources:
  - minios/finalizers
  verbs:
  - update
- apiGroups:
  - minio.bob.com
  resources:
  - minios/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
    - ""
  resources:
    - "*"
  verbs:
    - create
    - delete
    - deletecollection
    - get
    - list
    - patch
    - update
    - watch
- apiGroups:
    - apps
  resources:
    - "*"
  verbs:
    - create
    - delete
    - deletecollection
    - get
    - list
    - patch
    - update
    - watch
