apiVersion: v1
kind: Service
metadata:
  name: minio-operator-webhook-service
  labels:
    {{- include "minio-operator.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "minio-operator.selectorLabels" . | nindent 4 }}
